### ISSUE TITLE
tensorboardX issue

### ISSUE THREAD

**Issue by UltraSpecialException** [huggingface/transfer-learning-conv-ai#11]
`tb_logger = TensorboardLogger(log_dir=None)` in `train.py`

This line is causing this problem:

> Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/tnguyen/Desktop/recourse-nlp/transfer-learning-conv-ai/train.py", line 273, in <module>
    train()
  File "/Users/tnguyen/Desktop/recourse-nlp/transfer-learning-conv-ai/train.py", line 243, in train
    tb_logger = TensorboardLogger(log_dir=None)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ignite/contrib/handlers/tensorboard_logger.py", line 408, in __init__
    self.writer = SummaryWriter(logdir=log_dir)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboardX/writer.py", line 279, in __init__
    self.file_writer = FileWriter(logdir=log_dir, **kwargs)
TypeError: type object got multiple values for keyword argument 'logdir'

I initially had some tensorboadX issue, and had to revert it back to 1.6 instead of the latest 1.7 version. I also had to uninstall and install pytorch ignite again, I'm not sure what this means and I'm not sure if it's an ignite/tensorboardX problem or if I should be addressing this issue here. Please help :D

**Comment by g-karthik** [comment]
I already told @thomwolf about this here: https://github.com/huggingface/transfer-learning-conv-ai/issues/8#issuecomment-495021971

**Comment by UltraSpecialException** [comment]
Yeah I forgot to follow up, I figured it out and yeah my solution was like yours. Thank you!
