### ISSUE TITLE
Training with gpt2-large and got ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by GraphGrailAi** [huggingface/transfer-learning-conv-ai#37]
Hi, i have prepared my dataset with 2 personalities my.json (the same with the original 200mb dataset) and tried to start training with parameter `--model="gpt2-large"`, here is output:

```
joo@joo-tf:~/Документы/LocalRepository/transfer-learning-conv-ai$ python  ./train.py --gradient_accumulation_steps=4 --lm_coef=2.0 --max_history=2 --n_epochs=1 --num_candidates=4 --personality_permutations=2 --train_batch_size=1 --valid_batch_size=1 --dataset_path="my.json" --model="gpt2-large"
WARNING:./train.py:Running process -1
INFO:./train.py:Arguments: Namespace(dataset_cache='./dataset_cache', dataset_path='ze_personality_dataset_forgpt2.json', device='cuda', eval_before_start=False, fp16='', gradient_accumulation_steps=4, lm_coef=2.0, local_rank=-1, lr=6.25e-05, max_history=2, max_norm=1.0, mc_coef=1.0, model_checkpoint='gpt2-large', n_epochs=1, num_candidates=4, personality_permutations=2, train_batch_size=1, valid_batch_size=1)
INFO:./train.py:Prepare tokenizer, pretrained model and optimizer.
INFO:pytorch_transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-large-vocab.json from cache at /home/joo/.cache/torch/pytorch_transformers/69f8d734111f39eaa51a85907bfdc81a7ef42242d638ffab6f77df305402b2b2.1512018be4ba4e8726e41b9145129dc30651ea4fec86aa61f4b9f40bf94eac71
INFO:pytorch_transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-large-merges.txt from cache at /home/joo/.cache/torch/pytorch_transformers/38d28acc17953e356348dca948e152c653c0ccf5058a552eea30168e27f02046.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda
INFO:pytorch_transformers.modeling_utils:loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-large-config.json from cache at /home/joo/.cache/torch/pytorch_transformers/c8f887cdfff4327916f4b7ed06a379c0add42bd9c66e1fe3b4a5a8525a4b2678.bc44facd742477605da5434f20a32607ead98e78fff95c5ca9523e47b453e1ad
INFO:pytorch_transformers.modeling_utils:Model config {
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "finetuning_task": null,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 1024,
  "n_embd": 1280,
  "n_head": 20,
  "n_layer": 36,
  "n_positions": 1024,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "pruned_heads": {},
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torchscript": false,
  "vocab_size": 50257
}

INFO:pytorch_transformers.modeling_utils:loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-large-pytorch_model.bin from cache at /home/joo/.cache/torch/pytorch_transformers/bcc61dff8b1b03d0fd33a1eb1dc4db00875cae33296848155c6882d4bab03db4.999a50942f8e31ea6fa89ec2580cb38fa40e3db5aa46102d0406bcfa77d9142d
INFO:pytorch_transformers.tokenization_utils:Adding <bos> to the vocabulary
INFO:pytorch_transformers.tokenization_utils:Assigning <bos> to the bos_token key of the tokenizer
INFO:pytorch_transformers.tokenization_utils:Adding <eos> to the vocabulary
INFO:pytorch_transformers.tokenization_utils:Assigning <eos> to the eos_token key of the tokenizer
INFO:pytorch_transformers.tokenization_utils:Adding <pad> to the vocabulary
INFO:pytorch_transformers.tokenization_utils:Assigning <pad> to the pad_token key of the tokenizer
INFO:pytorch_transformers.tokenization_utils:Adding <speaker1> to the vocabulary
INFO:pytorch_transformers.tokenization_utils:Adding <speaker2> to the vocabulary
INFO:pytorch_transformers.tokenization_utils:Assigning ('<speaker1>', '<speaker2>') to the additional_special_tokens key of the tokenizer
INFO:./train.py:Prepare datasets
INFO:/home/joo/Документы/LocalRepository/transfer-learning-conv-ai/utils.py:Load tokenized dataset from cache at ./dataset_cache_GPT2Tokenizer
INFO:./train.py:Build inputs and labels
INFO:./train.py:Pad inputs and convert to Tensor
Traceback (most recent call last):
  File "./train.py", line 271, in <module>
    train()
  File "./train.py", line 175, in train
    train_loader, val_loader, train_sampler, valid_sampler = get_data_loaders(args, tokenizer)
  File "./train.py", line 102, in get_data_loaders
    dataset = pad_dataset(dataset, padding=tokenizer.convert_tokens_to_ids(SPECIAL_TOKENS[-1]))
  File "./train.py", line 43, in pad_dataset
    max_l = max(len(x) for x in dataset["input_ids"])
ValueError: max() arg is an empty sequence
```

I checked other issues, but no similar

**Comment by sshleifer** [comment]
Nothing to do with `gpt2-large`. my.json needs to have conversations, not just personalities if you want to use it for training. See [example_entry.py](https://github.com/huggingface/transfer-learning-conv-ai/blob/master/example_entry.py )

**Comment by GraphGrailAi** [comment]
> 
> 
> Nothing to do with `gpt2-large`. my.json needs to have conversations, not just personalities if you want to use it for training. See [example_entry.py](https://github.com/huggingface/transfer-learning-conv-ai/blob/master/example_entry.py)

Ok, `gpt2` i think too? (the same issue). 
Yes, maybe i was not clear: i used full copy of example_entry.py exactly, but with my data and got another issue. I then close this if no easy path to use gpt2(additional coding required)

**Comment by sshleifer** [comment]
Yeah this is about data not gpt2, closing.

**Comment by GraphGrailAi** [comment]
Hm, i was able to train with gpt2 and inference (but not with gpt2-large - not enough gpu memory

**Comment by monisha08041998** [comment]
> > Nothing to do with `gpt2-large`. my.json needs to have conversations, not just personalities if you want to use it for training. See [example_entry.py](https://github.com/huggingface/transfer-learning-conv-ai/blob/master/example_entry.py)
> 
> Ok, `gpt2` i think too? (the same issue).
> Yes, maybe i was not clear: i used full copy of example_entry.py exactly, but with my data and got another issue. I then close this if no easy path to use gpt2(additional coding required)

facing the same issue

**Comment by monisha08041998** [comment]
> Nothing to do with `gpt2-large`. my.json needs to have conversations, not just personalities if you want to use it for training. See [example_entry.py](https://github.com/huggingface/transfer-learning-conv-ai/blob/master/example_entry.py)

can you specify the minimum number of utterances we are suppose to use
