### ISSUE TITLE
Error when setting num_candidates=1 and in dataset there's only one candidate

### ISSUE THREAD

**Issue by dimeldo** [huggingface/transfer-learning-conv-ai#40]
When setting args.num_candidates to 1, and the actual length of the candidates list of each entry is 1, I get this error:
```
ERROR:ignite.engine.engine.Engine:Current run is terminating due to exception: For binary cases, y_pred must be comprised of 0's and 1's..
ERROR:ignite.engine.engine.Engine:Engine run is terminating due to exception: For binary cases, y_pred must be comprised of 0's and 1's..
ERROR:ignite.engine.engine.Engine:Engine run is terminating due to exception: For binary cases, y_pred must be comprised of 0's and 1's..
ERROR:ignite.engine.engine.Engine:Current run is terminating due to exception: For binary cases, y_pred must be comprised of 0's and 1's..
Traceback (most recent call last):
  File "./train-regular.py", line 271, in <module>
ERROR:ignite.engine.engine.Engine:Engine run is terminating due to exception: For binary cases, y_pred must be comprised of 0's and 1's..
ERROR:ignite.engine.engine.Engine:Engine run is terminating due to exception: For binary cases, y_pred must be comprised of 0's and 1's..
Traceback (most recent call last):
  File "./train-regular.py", line 271, in <module>
    train()
  File "./train-regular.py", line 263, in train
    train()
  File "./train-regular.py", line 263, in train
    trainer.run(train_loader, max_epochs=args.n_epochs)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 446, in run
    trainer.run(train_loader, max_epochs=args.n_epochs)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 446, in run
    self._handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 410, in _handle_exception
    self._handle_exception(e)
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 410, in _handle_exception
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 437, in run
    self._fire_event(Events.EPOCH_COMPLETED)
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 345, in _fire_event
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 437, in run
    func(self, *(event_args + args), **kwargs)
  File "./train-regular.py", line 217, in <lambda>
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 345, in _fire_event
```

**Comment by Riccorl** [comment]
I have the same problem, did you solve it?

**Comment by sshleifer** [comment]
I think num_candidates=1 won't work without significant code modification (removing multiple choice head). I think I've said something different in a different thread, which was wrong.

**Comment by Riccorl** [comment]
@sshleifer It seems like the problem is not the num_candidates=1, but instead the model recognise as binary classification where there is only one candidate in the utterance sample.

**Comment by dimeldo** [comment]
@sshleifer Do you have a workaround if I don't have multiple candidates for my dataset?

**Comment by sshleifer** [comment]
It would require  significant code modification.
 I'd start by 
- finding all mentions of multiple choice candidates (and removing them, fixing downstream if they are required)
- updating train.py to not use the CrossEntropyLoss/ or log it

there will probably be more bugs after that!

**Comment by nuttyartist** [comment]
@sshleifer Yeah, probably not worth changing the code that much. I was talking about a hack, like having the multiple-choice candidates be some random string, say "Something.". Would that work?

**Comment by dimeldo** [comment]
@sshleifer Yeah, probably not worth changing the code that much. I was talking about a hack, like having the multiple-choice candidates be some random string, say "Something.". Would that work?

**Comment by sshleifer** [comment]
Sounds like it might to me. Try it!
