### ISSUE TITLE
Difference in fine-tuned models linked in README and used in interact.py script

### ISSUE THREAD

**Issue by AmanTiwari1503** [huggingface/transfer-learning-conv-ai#82]
The pre-trained and fine-tuned model, given in the README of the repo under the 'Pretrained model' heading (linked [here](https://s3.amazonaws.com/models.huggingface.co/transfer-learning-chatbot/finetuned_chatbot_gpt.tar.gz)) is different from what gets used when we run `python interact.py`. <br>In the script utils.py, the link for the fine_tuned model has been given in the script as [https://s3.amazonaws.com/models.huggingface.co/transfer-learning-chatbot/gpt_personachat_cache.tar.gz](https://s3.amazonaws.com/models.huggingface.co/transfer-learning-chatbot/gpt_personachat_cache.tar.gz).
<br> Are these two different models because when I tried to run the earlier fine-tuned model which was linked with the repo as a model-checkpoint with interact.py, following error was obtained - <br>
Command used - `python3 ./interact.py --model_checkpoint='./finetuned_chatbot_gpt'`<br>
Error:
Traceback (most recent call last):
  File "./interact.py", line 155, in <module>
    run()
  File "./interact.py", line 128, in run
    model = model_class.from_pretrained(args.model_checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py", line 558, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for OpenAIGPTLMHeadModel:
	size mismatch for transformer.tokens_embed.weight: copying a param with shape torch.Size([40483, 768]) from checkpoint, the shape in current model is torch.Size([40478, 768]).<br>
While just running `python3 interact.py`, the result was fine.
Kindly see to this issue

**Comment by alabrashJr** [comment]
I think the model shared is a GPT2LMHeadModel however the tokenizer is OpenAIGPTTokenizer lol!
