### ISSUE TITLE
tb_logger Error: got an unexpected keyword argument 'another_engine'

### ISSUE THREAD

**Issue by RVirmoors** [huggingface/transfer-learning-conv-ai#85]
Hi, I'm trying to run train.py on Google Colab. 
interact.py works fine, but when trying to fine-tune, "!python train.py" (with or without arguments) stops here:

> INFO:train.py:Build inputs and labels
> INFO:train.py:Pad inputs and convert to Tensor
> INFO:train.py:Build train and validation dataloaders
> INFO:train.py:Train dataset (Batch, Candidates, Seq length): torch.Size([131438, 2, 285])
> INFO:train.py:Valid dataset (Batch, Candidates, Seq length): torch.Size([7801, 20, 185])
> Traceback (most recent call last):
>   File "train.py", line 267, in <module>
>     train()
>   File "train.py", line 249, in train
>     tb_logger.attach(evaluator, log_handler=OutputHandler(tag="validation", metric_names=list(metrics.keys()), another_engine=trainer), event_name=Events.EPOCH_COMPLETED)
> TypeError: __init__() got an unexpected keyword argument 'another_engine'

(this is using the CPU runtime. If I try the GPU, I don't even get this far... interact.py crashes too)

could it be a tensorboard version incompatibility? i've got the following installed:
tensorboard              2.2.2          
tensorboard-plugin-wit   1.7.0          
tensorboardcolab         0.0.22         
tensorboardX             1.8  
pytorch-ignite           0.5.0

(just tried it locally and I'm getting the same error.)

**Comment by RVirmoors** [comment]
OK I simply removed "another_engine=trainer" and it seems to work fine.

**Comment by ashantanu** [comment]
I tried changing pytorch-ignite version to 0.3.0 and that worked.
